INPUT_DF: config/samples.tsv

OUTPUT:
    RUN:
        PEAKS: True
        QC: False
    BAMPROCESS_PARAMS: -q 30
    MACS3_TYPE:
        - callsummit

REF:
    NAME: hg19
    FA: ...
    BWA_IDX: ...
    CHROM_SIZES: ...

CUT_ADAPTERS: True

ADAPTER_FWD: CTGTCTCTTATA
ADAPTER_REV: CTGTCTCTTATA