
INPUT_DF: config/samples.tsv

OUTPUT:
    MACS3_TYPE:
        - callsummit
    RUN:
        PEAKS: True
        QC: False

REF:
    NAME: hg19
    FA: ...
    BWA_IDX: ...
    CHROM_SIZES: ...

CUT_ADAPTERS: True

ADAPTER_FWD: CTGTCTCTTATA
ADAPTER_REV: CTGTCTCTTATA

BAMPROCESS_PARAMS: -q 30

